<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Location::truncate();
        $locations = [
            'Kashaydanga',
            'Shahajipara',
            'Raipara',
            'Aduburi',
            'Ghuripara',
            'Salagacha',
            'Hargram',
            'Hordupur',
            'Hargagram Newpara',
            'Hargram Ranidighi',
            'Hargram Colony',
            'Hargram Bidirpara',
            'Nagarpara',
            'Mollapara',
            'Sheikhpara',
            'Tenpukur',
            'Baharampur',
            'New Bisimla',
            'Laksmipur',
            'Hargam Bazar',
            'Bulanpur',
            'Goalpara',
            'Keshabpur',
            'Nawabganj',
            'Rajpara',
            'Mahisbathan',
            'Kulupara',
            'Bhatapara',
            'Laxmipur',
            'Chandipur',
            'vatapara',
            'Serampore',
            'Betiapara',
            'Kazihaata',
            'Sepipara',
            'Hosnaganj',
            'Dargapara',
            'Zodhash',
            'Sherusarpara',
            'Hematch',
            'Goalpara',
            'Wapda Colony',
            'Medical campus',
            'Hetmakhan Sajipara',
            'Hetamkhana',
            'Malopara(western part)',
            'Rajahata',
            'Kadirganj',
            'Matherpara',
            'Karikarpara',
            'Shahajipara',
            'Fadkipara',
            'Kumara Para',
            'Sahib ganj',
            'Saheb Bazar',
            'Queen market',
            'Malopara (eastern part)',
            'Kadirganj(Boalia)',
            'Dakkharbora',
            'Suburb',
            'Terokhadia',
            'Sapura',
            'Dakhirbona',
            'Sapura industrial area',
            'Matherdanga',
            'Bakhtiarabad',
            'Kirender',
            'Bigger',
            'Noadapara',
            'Assam Colony',
            'Poba',
            'Poba Rice Mill',
            'Ahmad Nagar',
            'Firozabad',
            'Poba new fringe',
            'Poba, TTC',
            'Poba Mathpukur',
            'Shalbagan',
            'Headline Colony',
            'Small forest colony',
            'Small village',
            'Shiroil Colony',
            'Railway Colony',
            'Boalia Para',
            'Sultanabad',
            'Ballobganj',
            'Headline',
            'Sagorpara',
            'Rampur Bazar',
            'Chansons chalk',
            'Ghooramara',
            'Ramchandra Pur(west)',
            'Bad Kajala',
            'Ramchandra Pur (including Purbash Ahmadpur)',
            'Talaimari',
            'Queen Nagar',
            'Mehrchandi',
            'Chakpar Meherchandi',
            'Engineering College',
            'Tikpara',
            'Mir Chalk',
            'Raninagar',
            'Devi Shipping',
            'Baliapukur',
            'Shirley Mathpukur',
            'Over the groom',
            'Cajala',
            'Dharampur',
            'Talaimari (eastern part)',
            'Bad kajla (eastern part)',
            'Grazing land',
            'Sahtbariya',
            'Khojapur',
            'Dashmari',
            'Care Satbariya',
            'Sishampur Dashmari',
            'University campus',
            'Mirzapur',
            'Mascata Dighi(Mehrchandi)',
            'Budhapara',
            'Mohanpur',
            'Fruit garden',
            'Agricultural Firm',
            'Science and Industrial Laboratory',
            'Mehrchandi Badhupara',
        ];
        foreach($locations as $location){

            Location::create([
                'location'  => $location,
            ]);
        }
    }
}
